siteTitle="OpenPOA (POA) - Fast & Reliable Ethereum Sidechain with known independent validators"
linkPrefix = ""
theme="violet"
themeSecondary="violet"
[[menuItems]]
name = "Github"
link = "https://github.com/openpoa"
icon = "icon github"
